name: "Deploy"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Every Day

jobs:
  convo_crons:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: Install DCL
      run: yarn install -g decentraland
    - name: Export Project
      run: yarn export
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: export
